server.port=8080
spring.application.name=ONESTEP-be

# DataSource
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=onestep;encrypt=false;trustServerCertificate=true
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:OnestepDev!2026}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# SQL 초기화
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.separator=GO
